import Menu from "@/components/Menu/Menu";
import "./globals.css";
import { Boogaloo, Bungee, Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const bungee = Bungee({
  subsets: ["latin"],
  variable: "--font-bungee",
  weight: "400",
});

const boogaloo = Boogaloo({
  subsets: ["latin"],
  variable: "--font-boogaloo",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
        ${inter.variable} 
        ${bungee.variable}
        ${boogaloo.variable}`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
